function a = file_select(src,event)
[filename, pathname, ~] = uigetfile( ...
    {...   
    '*.mat;*.trs','所有数据类型';...
    '*.mat','MAT 格式 (*.mat)'; ...
    '*.trs','trs 格式 (*.trs)'; ...
    '*.*',  '所有文件 (*.*)'}, ...
    '选择文件', ...
    'MultiSelect', 'on');

% m = load([pathname filename]);
if ~isempty(filename)
    m = matfile([pathname filename]);
    [pathstr,name,ext] = fileparts(filename);
    if ext == '.trs'
        name = ['trs_' name];
    end
    assignin('base', name, m);
end
end