function file_select(src,event)
[filename, pathname, ~] = uigetfile( ...
    {   '*.mat;*.trs','所有数据类型';...
        '*.mat','MAT 格式 (*.mat)'; ...
        '*.trs','trs 格式 (*.trs)'; ...
        '*.*',  '所有文件 (*.*)'}, ...
    '选择文件', ...
    'MultiSelect', 'on');
% [pathname filename];
persistent m;
m = load([pathname filename]);
end